import subprocess

subprocess.run('schema-detect data/csv/sales_header.csv', shell=True, check=True)
subprocess.run('schema-detect data/csv/sales_no_header.csv --fmt yaml --output-dir ./cli/ --output-file schema_no_header.yml', shell=True, check=True)
subprocess.run('schema-detect data/csv/very_wide.csv --fmt yaml --output-dir ./cli/ --output-file schema_wide.yml', shell=True, check=True)
subprocess.run('schema-detect data/csv/sales_utf8_sig.csv --fmt yaml --output-dir ./cli/ --output-file schema_utf8.yml', shell=True, check=True)
subprocess.run('schema-detect data/orc/TestOrcFile.testDate1900.orc --fmt yaml --output-dir ./cli/ --output-file schema_orc.yml', shell=True, check=True)
subprocess.run('schema-detect data/avro/weather.avro --fmt yaml --output-dir ./cli/ --output-file schema_avro.yml', shell=True, check=True)
subprocess.run('schema-detect data/parquet/v0.7.1.all-named-index.parquet --fmt yaml --output-dir ./cli/ --output-file schema_pqt.yml', shell=True, check=True)
subprocess.run('schema-detect data/delta/people_countries_delta_dask/ --fmt yaml --output-dir ./cli/ --output-file schema_delta.yml', shell=True, check=True)
subprocess.run('schema-detect data/json/events.ndjson --fmt yaml --output-dir ./cli/ --output-file schema_json.yml', shell=True, check=True)
subprocess.run('schema-detect data/xml/books.xml --fmt yaml --output-dir ./cli/ --output-file schema_xml.yml', shell=True, check=True)
subprocess.run('schema-detect data/json/events.ndjson --fmt dict', shell=True, check=True)
subprocess.run('schema-detect data/csv/sales_header.csv --fmt yaml --output-dir ./cli/', shell=True, check=True)
subprocess.run('schema-detect data/csv/sales_20250101.csv --fmt json --output-dir ./cli/ --output-file schema_date.json', shell=True, check=True)